[2022-06-12 17:26:24,592] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-cdc_load.csv_to_database manual__2022-06-12T17:26:21.580928+00:00 [queued]>
[2022-06-12 17:26:24,602] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-cdc_load.csv_to_database manual__2022-06-12T17:26:21.580928+00:00 [queued]>
[2022-06-12 17:26:24,602] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 17:26:24,602] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-12 17:26:24,602] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-12 17:26:24,614] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): csv_to_database> on 2022-06-12 17:26:21.580928+00:00
[2022-06-12 17:26:24,619] {standard_task_runner.py:52} INFO - Started process 4878 to run task
[2022-06-12 17:26:24,622] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'T-dbt-job-cdc_load', 'csv_to_database', 'manual__2022-06-12T17:26:21.580928+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/dbt_test.py', '--cfg-path', '/tmp/tmp_0kcn0gh', '--error-file', '/tmp/tmpjp5iq9vg']
[2022-06-12 17:26:24,622] {standard_task_runner.py:80} INFO - Job 183: Subtask csv_to_database
[2022-06-12 17:26:24,672] {task_command.py:370} INFO - Running <TaskInstance: T-dbt-job-cdc_load.csv_to_database manual__2022-06-12T17:26:21.580928+00:00 [running]> on host e926c0944008
[2022-06-12 17:26:24,741] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuelolle@yahoo.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=T-dbt-job-cdc_load
AIRFLOW_CTX_TASK_ID=csv_to_database
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T17:26:21.580928+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-12T17:26:21.580928+00:00
[2022-06-12 17:26:24,750] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-12 17:26:24,754] {postgres.py:127} INFO - Running copy expert: COPY analytics_stage.users_cdc FROM STDIN, filename: /opt/airflow/dags/docker_job/data/users.csv
[2022-06-12 17:26:24,759] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-12 17:26:24,770] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-12 17:26:24,774] {postgres.py:127} INFO - Running copy expert: COPY analytics_stage.walls_cdc FROM STDIN, filename: /opt/airflow/dags/docker_job/data/walls.csv
[2022-06-12 17:26:24,779] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-12 17:26:24,784] {python.py:173} INFO - Done. Returned value was: None
[2022-06-12 17:26:24,797] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=T-dbt-job-cdc_load, task_id=csv_to_database, execution_date=20220612T172621, start_date=20220612T172624, end_date=20220612T172624
[2022-06-12 17:26:24,834] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-12 17:26:24,867] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
