[2022-06-19 22:49:24,380] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-facts.dbt_cleanup-facts manual__2022-06-19T22:48:42.206997+00:00 [queued]>
[2022-06-19 22:49:24,389] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-facts.dbt_cleanup-facts manual__2022-06-19T22:48:42.206997+00:00 [queued]>
[2022-06-19 22:49:24,389] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 22:49:24,389] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-19 22:49:24,389] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 22:49:24,401] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_cleanup-facts> on 2022-06-19 22:48:42.206997+00:00
[2022-06-19 22:49:24,406] {standard_task_runner.py:52} INFO - Started process 1505 to run task
[2022-06-19 22:49:24,408] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'T-dbt-job-facts', 'dbt_cleanup-facts', 'manual__2022-06-19T22:48:42.206997+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/dbt_model.py', '--cfg-path', '/tmp/tmpzbdpy54s', '--error-file', '/tmp/tmprkxrqhro']
[2022-06-19 22:49:24,409] {standard_task_runner.py:80} INFO - Job 58: Subtask dbt_cleanup-facts
[2022-06-19 22:49:24,453] {task_command.py:370} INFO - Running <TaskInstance: T-dbt-job-facts.dbt_cleanup-facts manual__2022-06-19T22:48:42.206997+00:00 [running]> on host 7cbff6e51e2a
[2022-06-19 22:49:24,511] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuelolle@yahoo.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=T-dbt-job-facts
AIRFLOW_CTX_TASK_ID=dbt_cleanup-facts
AIRFLOW_CTX_EXECUTION_DATE=2022-06-19T22:48:42.206997+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-19T22:48:42.206997+00:00
[2022-06-19 22:49:24,512] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-19 22:49:24,512] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm -rf /tmp/facts && rm -rf /tmp/tmp* 2>/dev/null || exit 0']
[2022-06-19 22:49:24,522] {subprocess.py:85} INFO - Output:
[2022-06-19 22:49:24,626] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-19 22:49:24,652] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=T-dbt-job-facts, task_id=dbt_cleanup-facts, execution_date=20220619T224842, start_date=20220619T224924, end_date=20220619T224924
[2022-06-19 22:49:24,702] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-19 22:49:24,750] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
